services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tourze\RAGFlowApiBundle\Controller\:
    resource: '../../Controller/'

  Tourze\RAGFlowApiBundle\Repository\:
    resource: '../../Repository/'

  Tourze\RAGFlowApiBundle\Service\:
    resource: '../../Service/'
    public: true

  Tourze\RAGFlowApiBundle\Command\:
    resource: '../../Command/'

  Tourze\RAGFlowApiBundle\Client\:
    resource: '../../Client/'
    public: true

  Tourze\RAGFlowApiBundle\Builder\:
    resource: '../../Builder/'
    public: true

  Tourze\RAGFlowApiBundle\Orchestrator\:
    resource: '../../Orchestrator/'

  Tourze\RAGFlowApiBundle\Validator\:
    resource: '../../Validator/'

  Tourze\RAGFlowApiBundle\Context\:
    resource: '../../Context/'

  Tourze\RAGFlowApiBundle\Helper\:
    resource: '../../Helper/'
    public: true

  # 接口别名
  Tourze\RAGFlowApiBundle\Service\RAGFlowInstanceManagerInterface:
    alias: Tourze\RAGFlowApiBundle\Service\RAGFlowInstanceManager
